# Generated by Django 4.0.3 on 2022-03-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
