# Generated by Django 4.0.3 on 2022-03-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_about_about_img_alter_about_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('work_image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
