# Generated by Django 4.0.3 on 2022-03-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
