# Generated by Django 4.0.3 on 2022-03-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_works_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
